### ISSUE TITLE
When mentioning a slack user, it should create a clickable link to that user

### ISSUE THREAD

**Issue by TangentFoxy** [Lomeli12/MCSlack#3]
I believe you need to detect when `@name` matches a username and convert it to `<@user_id>`

Dunno if this is even possible, but yea.

**Comment by Lomeli12** [comment]
Possible, but requires registering application with slack to use their Web API. https://api.slack.com/methods/users.info

**Comment by Lomeli12** [comment]
The API will only give me the username and not a link to the profile (is that even public?). Also, MC messages can only do 1 link per message in chat, so if someone puts `@user http://google.com`, I'm going to prioritize the actually URL rather than a link to the user profile.
